### PR TITLE
add map

### PR DESCRIPTION
**Pull request by GregoireHebert**
## Description

Add a map method in the  NumArray class

## Motivation and context

When dealing with a simple neural network, I need to apply a specific activation function on each value. At the moment only abs does apply a function to everything. Adding map allow the user to apply the function he wants. In my case sigmoid.

## How has this been tested?

There is nothing much to test as most of the work belong to the user :)

## Screenshots (if appropriate)

Capture d’écran 2019-10-18 à 19 45 40

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by GordonLesti** [comment]
Hello @GregoireHebert 
thank you very much for the PR. Would you like to merge the [branch 1.1](https://github.com/NumPHP/NumPHP/tree/1.1) again into your branch? As branch 1.1 was outdated, I made it passing Travis again.
Can you also please make your tests passing?

Best Regards
Gordon

**Comment by GregoireHebert** [comment]
Hey @GordonLesti :)
Sure I'll do that :)
And speaking of branches, I selected the 1.1 but it's an additional feature... I thought 1.2 was a best choice. WDYT ?

I'll do the merge in the train tonight.

**Comment by GregoireHebert** [comment]
Seems good to me :)

**Comment by GregoireHebert** [comment]
ping @GordonLesti  :D

**Comment by GordonLesti** [comment]
Hello @GregoireHebert 
I made a few changes, regarding my comments from above and merged everything into [branch 1.2](https://github.com/NumPHP/NumPHP/tree/1.2) as you suggested with the following [commit](https://github.com/NumPHP/NumPHP/commit/cae62d83debee8b0f1e1c53e060c6688014dc0c8). Are you fine with that changes?

Best Regards
Gordon

**Comment by GregoireHebert** [comment]
Yup sure ! Fine to me :)

**Comment by GordonLesti** [comment]
I have created a tag https://github.com/NumPHP/NumPHP/releases/tag/v1.2.0

**Pull request closed without merging**
